site_name: 厦门大学·RoboMaster·运营管理<img src='https://cdn.img.wenhairu.com/images/2020/10/11/CksbD.png'>
site_favicon: favicon.ico
site_url: 
nav:
- 战队信息:
    - 团队介绍: TeamIntroduction.md
    - 赛事介绍: CompetitionIntro.md
    - 工作内容: WorkContent.md
    - 联系方式: ContactDetails.md
- 宣传相关:
    - 平台运营: PlatformOperation.md
    - 宣传海报: PropagandaPoster.md
    - 活动策划: EventsPlanning.md
- 商业相关:
    - 招商单页: CommercialPage.md
    - 赞助权益: SponsorRights.md
    - 合作公示: PartnerAnnouncement.md
- 财务相关:
    - 财务流程: FinancialProcess.md
    - 财务规范: FinancialSpecification.md
    
theme: readthedocs
site_author: ASR-Crash
copyright: Copyright © 2021 ASR-Crash